// CairnX token/name support — byte-exactness of the locally-built transfer record,
// decimals-aware formatting, clear-sign decode of every cairnx:v1 record type, and
// graceful degradation when the read API is unreachable.
//
// ORACLE: every `uri` + payloadHash fixture below was generated by the canonical
// @inversealtruism/cairnx-core builders (the convention's reference implementation),
// so the wallet's isolated copy is pinned byte-for-byte to the resolver's reality.
import { buildTransfer, buildNameProfile, canonicalJson, cairnxPayloadHash, formatUnits, parseUnits, decodeCairnxRecord, CAIRNX_DOMAIN, CAIRNX_PROPOSE_FEE } from "../src/core/cairnx.js";
import { describe, cairnxDescribe, costLine, nameCautionHtml, reresolveUnchanged } from "../src/popup/clearsign.js";
import { Wallet } from "../src/core/wallet.js";
import { memoryStore } from "../src/core/storage.js";
import { mkCoin, txReply } from "./_coin.js";

declare const process: { exit(code: number): void };
let pass = 0, fail = 0;
const check = (n: string, c: boolean) => { c ? (pass++, console.log("  ✅ " + n)) : (fail++, console.log("  ❌ " + n)); };
const ADDR_AB = "0x" + "ab".repeat(20);
const ADDR_CD = "0x" + "cd".repeat(20);

// ─── 1) transfer record: canonical-JSON byte-exactness vs cairnx-core fixtures ───
{
  const t = buildTransfer({ ticker: "CAIRN", amount: "150000000", to: ADDR_AB });
  check("transfer uri is byte-exact canonical JSON (cairnx-core fixture)",
    t.uri === `{"amount":"150000000","t":"transfer","ticker":"CAIRN","to":"${ADDR_AB}","v":1}`);
  check("transfer payloadHash == sha256(uri) (cairnx-core fixture)",
    t.payloadHash === "0xfbaacb83d1a004bf8a101ac303b627bdabf70a9a897fb9404eefcabd78b2d816");
  const t2 = buildTransfer({ ticker: "TKN", amount: "42", to: "0x6EDA635DEAA2F710213942CC97C19B7E008FC694" }); // mixed case in
  check("second fixture: uri byte-exact + recipient lowercased in the record",
    t2.uri === `{"amount":"42","t":"transfer","ticker":"TKN","to":"0x6eda635deaa2f710213942cc97c19b7e008fc694","v":1}`);
  check("second fixture: payloadHash matches cairnx-core",
    t2.payloadHash === "0x660c5e8b26c9c024d63aab09835a460efbe8727fc2933b0dd1c909e66005325b");
  check("payloadHash is recomputable from the parsed record", cairnxPayloadHash(JSON.parse(t.uri)) === t.payloadHash);
  check("canonicalJson sorts keys + drops undefined + no whitespace",
    canonicalJson({ b: 1, a: "x", c: undefined }) === `{"a":"x","b":1}`);

  const rej = (p: any) => { try { buildTransfer(p); return false; } catch { return true; } };
  check("buildTransfer rejects a bad ticker", rej({ ticker: "no", amount: "1", to: ADDR_AB }) && rej({ ticker: "1ABC", amount: "1", to: ADDR_AB }));
  check("buildTransfer rejects a bad recipient", rej({ ticker: "TKN", amount: "1", to: "0x1234" }));
  check("buildTransfer rejects zero / negative / non-integer / leading-zero amounts",
    rej({ ticker: "TKN", amount: "0", to: ADDR_AB }) && rej({ ticker: "TKN", amount: "-1", to: ADDR_AB })
    && rej({ ticker: "TKN", amount: "1.5", to: ADDR_AB }) && rej({ ticker: "TKN", amount: "01", to: ADDR_AB }));
  check("buildTransfer rejects an amount above 2^96-1", rej({ ticker: "TKN", amount: (1n << 96n).toString(), to: ADDR_AB }));
  check("buildTransfer accepts the max amount 2^96-1", !rej({ ticker: "TKN", amount: ((1n << 96n) - 1n).toString(), to: ADDR_AB }));
}

// ─── 2) decimals formatting (display = baseUnits / 10^decimals) ───────────────
{
  check("formatUnits: 8 decimals", formatUnits("150000000", 8) === "1.5");
  check("formatUnits: 0 decimals (whole units)", formatUnits("42", 0) === "42");
  check("formatUnits: smallest 8-dec unit", formatUnits("1", 8) === "0.00000001");
  check("formatUnits: zero", formatUnits("0", 8) === "0");
  check("formatUnits: trailing zeros trimmed", formatUnits("120000000", 8) === "1.2");
  check("formatUnits: exact at full precision", formatUnits("123456781", 8) === "1.23456781");
  check("formatUnits: huge supply stays exact (BigInt, no float)", formatUnits("2100000000000000", 8) === "21000000");
  check("formatUnits: garbage → '?' (never NaN)", formatUnits("abc", 8) === "?" && formatUnits("-5", 8) === "?");
  check("formatUnits: garbage decimals treated as 0", formatUnits("42", "evil" as any) === "42" && formatUnits("42", 99) === "42");
  check("parseUnits: human → base units", parseUnits("1.5", 8) === "150000000");
  check("parseUnits: whole number, 0 decimals", parseUnits("42", 0) === "42");
  check("parseUnits: too many decimal places → null", parseUnits("0.000000001", 8) === null && parseUnits("1.5", 0) === null);
  check("parseUnits: junk → null", parseUnits("abc", 8) === null && parseUnits("1.2.3", 8) === null && parseUnits("-1", 8) === null && parseUnits("", 8) === null);
  check("parseUnits: trailing-dot / 1e8 notation rejected", parseUnits("1.", 8) === null && parseUnits("1e8", 8) === null);
  check("parseUnits: round-trips with formatUnits", formatUnits(parseUnits("0.00000001", 8)!, 8) === "0.00000001");
  check("parseUnits: overflow past 2^96-1 → null", parseUnits("99999999999999999999999999999999", 8) === null);
  check("locked amounts format the same way", formatUnits("50000000", 8) === "0.5");
}

// ─── 3) clear-sign decode: every cairnx:v1 record type (REAL cairnx-core uris) ───
// Each entry: [type, uri, payloadHash from the cairnx-core oracle, substrings the
// structured clear-sign view MUST surface].
const RECORDS: [string, string, string, string[]][] = [
  ["deploy", `{"decimals":8,"mint":"issuer","name":"Cairn","supply":"2100000000000000","t":"deploy","ticker":"CAIRN","v":1}`,
    "0xcfe2a4e58fbcc1ce9de97308071eb48e7952a41c6ecee43e3dfa6875b17151a0", ["token deploy", "CAIRN", "2100000000000000", "decimals: 8", "issuer"]],
  ["mint", `{"amount":"100000000","t":"mint","ticker":"CAIRN","v":1}`,
    "0x2f0b0d5a7bd25f768c157d1dcaca116b9b2eb147257ba7c834cc32d34d76f27f", ["token mint", "CAIRN", "100000000"]],
  ["transfer", `{"amount":"150000000","t":"transfer","ticker":"CAIRN","to":"${ADDR_AB}","v":1}`,
    "0xfbaacb83d1a004bf8a101ac303b627bdabf70a9a897fb9404eefcabd78b2d816", ["token transfer", "CAIRN", "150000000", ADDR_AB, "base units"]],
  ["offer", `{"give":{"amount":"500000000","ticker":"CAIRN"},"t":"offer","v":1,"want":{"payto":"${ADDR_CD}","value":"1000000000"}}`,
    "0x87d7efafbc792259a6077ca077b053e020abed01452938e482db220ce6e74eeb", ["CairnX offer", "CAIRN", "500000000", "10 CSD", ADDR_CD]],
  ["bid", `{"give":{"value":"5000000000"},"t":"bid","v":1,"want":{"name":"satoshi"}}`,
    "0x26e1d8d751d7acd7fcad85a90be64e7e8c4886642ef95c8f916685ba6b6c05a0", ["CairnX bid", "50 CSD", "satoshi.csd"]],
  ["ocancel", `{"t":"ocancel","ticker":"CAIRN","v":1}`,
    "0xbcb2c0dbc97b976d607900b72f76345c04966486ab1f4f8af0a51b287e73993a", ["cancel offers", "CAIRN"]],
  ["ocancel-all", `{"t":"ocancel","v":1}`,
    "0xb049ba1b57455b88958ddcd233e51261ff0bf3e365532c95e90fcb631ee712fe", ["cancel offers", "ALL"]],
  ["name", `{"name":"satoshi","salt":"a1b2c3d4e5f60718","t":"name","v":1}`,
    "0xe7bd075d10847e2aa7fd3df53c3ca4164555120171790e1c55fb1d2984d1a100", ["name claim", "satoshi.csd"]],
  ["nrenew", `{"name":"satoshi","t":"nrenew","v":1}`,
    "0x39e1f1d8fe702e5d6a604464605e4f481144b88229938b2619c86f3a76723aad", ["name renewal", "satoshi.csd"]],
  ["tmeta", `{"hash":"0x${"7e".repeat(32)}","t":"tmeta","ticker":"CAIRN","v":1}`,
    "0xa8ce7912affc29a4d090ccd80371a29a5d0e13678cac7ded5259ba27e55ea6d8", ["token metadata", "CAIRN", "7e".repeat(32)]],
  ["ncommit", `{"commit":"0x${"11".repeat(32)}","t":"ncommit","v":1}`,
    "0x2428323f80b2858e430174b9e30bc2df146ca9b34961df4fe997ed73826db02c", ["name commit", "11".repeat(32)]],
  ["nxfer", `{"name":"satoshi","t":"nxfer","to":"${ADDR_AB}","v":1}`,
    "0x9b46a624241cf2ae22441ff65dae52d2396511d7cfc1d197ea6c886afcd4b8d0", ["name transfer", "satoshi.csd", ADDR_AB]],
  ["nset", `{"addr":"${ADDR_CD}","name":"satoshi","t":"nset","v":1}`,
    "0x22ea436ed94a3af8465f5f3f491707e350f14007d1a04f0a78eff4b5f858a74d", ["address record", "satoshi.csd", ADDR_CD]],
  ["nprofile", `{"name":"satoshi","p":{"avatar":"https://a.co/x.png","com.twitter":"satoshi","display":"Satoshi"},"t":"nprofile","v":1}`,
    "0x2534b3e7e47ef746054197113c843bc9579a65dd6bbc7e724a55b86f16a20d4e", ["identity profile", "satoshi.csd", "avatar", "com.twitter", "Satoshi", "does NOT change where funds go"]],
];
for (const [t, uri, ph, wants] of RECORDS) {
  const dec = decodeCairnxRecord(uri, ph);
  check(`decode(${t}) returns the record`, dec !== null && typeof dec!.t === "string");
  const html = cairnxDescribe(uri, ph);
  check(`clear-sign(${t}) is structured + surfaces every key field`, html !== null && wants.every((w) => html!.includes(w)));
  // full describe() integration: a dApp propose in cairnx:v1 renders structured, NOT a raw JSON blob
  const full = describe({ method: "propose", params: { domain: CAIRNX_DOMAIN, payloadHash: ph, uri, fee: CAIRNX_PROPOSE_FEE } });
  check(`describe(propose ${t}) replaces the raw uri blob with the structured view`,
    !full.includes("&quot;t&quot;") && wants.every((w) => full.includes(w)) && full.includes(ph));
}

// ─── 3b) v1.9 nprofile (doc 36): build parity, app-layer key block, clear-sign ───
{
  const built = buildNameProfile({ name: "satoshi", profile: { avatar: "https://a.co/x.png", "com.twitter": "satoshi", display: "Satoshi" } });
  check("buildNameProfile: uri is byte-exact canonical JSON (cairnx-core fixture)",
    built.uri === `{"name":"satoshi","p":{"avatar":"https://a.co/x.png","com.twitter":"satoshi","display":"Satoshi"},"t":"nprofile","v":1}`);
  check("buildNameProfile: payloadHash matches the cairnx-core oracle",
    built.payloadHash === "0x2534b3e7e47ef746054197113c843bc9579a65dd6bbc7e724a55b86f16a20d4e");
  // app-layer §9.4 enforcement (the WRITE path): a profile must never carry a send target
  const rejects = (profile: Record<string, unknown>) => { try { buildNameProfile({ name: "satoshi", profile: profile as Record<string, string> }); return false; } catch { return true; } };
  check("buildNameProfile REJECTS addr/address/coin keys (no send target in a cosmetic profile)",
    rejects({ addr: "0x1234" }) && rejects({ address: "x" }) && rejects({ coin: "btc" }));
  check("buildNameProfile REJECTS a bad-charset key (uppercase)", rejects({ Avatar: "x" }));
  check("buildNameProfile REJECTS a non-string value", rejects({ n: 5 }));
  check("buildNameProfile REJECTS an over-256-byte value", rejects({ bio: "x".repeat(257) }));
  check("buildNameProfile REJECTS >16 keys", rejects(Object.fromEntries(Array.from({ length: 17 }, (_, i) => ["k" + i, "v"]))));
  // empty profile = clear (valid)
  const cleared = buildNameProfile({ name: "satoshi", profile: {} });
  check("buildNameProfile: empty map (= clear) is byte-exact", cleared.uri === `{"name":"satoshi","p":{},"t":"nprofile","v":1}`);
  const clearHtml = cairnxDescribe(cleared.uri, cleared.payloadHash);
  check("clear-sign: an empty profile renders as 'clears' + cosmetic-only", clearHtml !== null && /clears/i.test(clearHtml!) && clearHtml!.includes("cosmetic only"));
  // decode is semantics-AGNOSTIC (mirrors the resolver): a hand-crafted record with an `addr` KEY still
  // decodes (the resolver would store it) — but the clear-sign WARNS it is cosmetic, not a send address.
  const addrUri = `{"name":"satoshi","p":{"addr":"0x1234"},"t":"nprofile","v":1}`;
  const addrPh = "0xc674115ac7a31003312ecb4bf50bdabb4e0bed5a0839db44d22e0bc9dbab73f6";
  check("decode: a profile with an `addr` KEY still decodes (resolver-agnostic lockstep)", decodeCairnxRecord(addrUri, addrPh) !== null);
  const addrHtml = cairnxDescribe(addrUri, addrPh);
  check("clear-sign WARNS when a cosmetic profile field is named like an address", addrHtml !== null && /NOT a send address/i.test(addrHtml!));
  // defense-in-depth (Gate-3): an address-shaped VALUE under a non-reserved key also warns
  const valRec = { v: 1, t: "nprofile", name: "satoshi", p: { wallet: "0x" + "ab".repeat(20) } };
  const valHtml = cairnxDescribe(canonicalJson(valRec), cairnxPayloadHash(valRec));
  check("clear-sign WARNS on an address-shaped VALUE under a non-reserved key", valHtml !== null && /NOT a send address/i.test(valHtml!));
  // dApp-controlled profile values must be HTML-escaped in the structured view
  const xssRec = { v: 1, t: "nprofile", name: "satoshi", p: { display: "<img src=x onerror=alert(1)>" } };
  const xssHtml = cairnxDescribe(canonicalJson(xssRec), cairnxPayloadHash(xssRec));
  check("clear-sign: dApp-controlled profile value is HTML-escaped", xssHtml !== null && !xssHtml!.includes("<img") && xssHtml!.includes("&lt;img"));
}

// hardening: anything that would be a resolver NO-OP must show RAW, never structured
{
  const t = RECORDS[2]; // transfer
  check("unknown record type → raw fallback (null)", cairnxDescribe(`{"t":"futurething","v":1}`, cairnxPayloadHash({ t: "futurething", v: 1 })) === null);
  check("NON-canonical uri (whitespace) → raw fallback", cairnxDescribe(`{ "amount":"1","t":"mint","ticker":"TKN","v":1 }`) === null);
  check("NON-canonical uri (key order) → raw fallback", cairnxDescribe(`{"t":"mint","amount":"1","ticker":"TKN","v":1}`) === null);
  check("payload-hash mismatch → raw fallback (hash doesn't commit to the uri shown)", cairnxDescribe(t[1], "0x" + "00".repeat(32)) === null);
  check("schema-invalid record (bad ticker) → raw fallback", cairnxDescribe(`{"amount":"1","t":"transfer","ticker":"bad","to":"${ADDR_AB}","v":1}`) === null);
  check("not-JSON / array / huge uri → raw fallback",
    cairnxDescribe("not json") === null && cairnxDescribe("[1,2]") === null && cairnxDescribe(`{"t":"mint","ticker":"TKN","v":1,"x":"${"a".repeat(600)}"}`) === null);
  // resolver lockstep (cairnx-core v0.1.6 exact-key allowlist + ts SafeInteger; audit M1/FORK-1): a
  // value-bearing record with a decoy extra key, or a ts outside the safe-integer range, canonicalizes
  // differently across languages and the resolver no-ops it — so the wallet must NOT decode it either.
  { const xk = { v: 1, t: "transfer", ticker: "TKN", amount: "1", to: ADDR_AB, ZZ: "decoy" };
    check("extra-key transfer → raw fallback (resolver exact-key lockstep)", cairnxDescribe(canonicalJson(xk), cairnxPayloadHash(xk)) === null); }
  { const bigts = { v: 1, t: "transfer", ticker: "TKN", amount: "1", to: ADDR_AB, ts: 9007199254740993 };
    check("transfer ts > 2^53 → raw fallback (determinism SafeInteger)", cairnxDescribe(canonicalJson(bigts), cairnxPayloadHash(bigts)) === null); }
  { const okts = { v: 1, t: "transfer", ticker: "TKN", amount: "1", to: ADDR_AB, ts: 1700000000 };
    check("transfer with a normal ts still decodes (no over-rejection)", cairnxDescribe(canonicalJson(okts), cairnxPayloadHash(okts)) !== null); }
  const fullUnknown = describe({ method: "propose", params: { domain: CAIRNX_DOMAIN, payloadHash: cairnxPayloadHash({ t: "futurething", v: 1 }), uri: `{"t":"futurething","v":1}`, fee: 1 } });
  check("describe(propose, unknown cairnx shape) still shows the RAW uri", fullUnknown.includes("futurething") && fullUnknown.includes("uri:"));
  const fullOther = describe({ method: "propose", params: { domain: "csd:apps", payloadHash: "0x" + "11".repeat(32), uri: t[1], fee: 1 } });
  check("a cairnx-looking uri in a NON-cairnx domain is NOT decoded", fullOther.includes("Post a proposal") && !fullOther.includes("token transfer"));
  // a memo is dApp-controlled text → must be HTML-escaped in the structured view
  const memoRec = { v: 1, t: "transfer", ticker: "TKN", amount: "1", to: ADDR_AB, memo: "<img src=x onerror=alert(1)>" };
  const memoHtml = cairnxDescribe(canonicalJson(memoRec), cairnxPayloadHash(memoRec));
  check("dApp-controlled memo is HTML-escaped in the structured view", memoHtml !== null && !memoHtml!.includes("<img") && memoHtml!.includes("&lt;img"));
  // propose-with-outputs keeps the funds-leaving warning even when structured
  const withOuts = describe({ method: "propose", params: { domain: CAIRNX_DOMAIN, payloadHash: t[2], uri: t[1], fee: CAIRNX_PROPOSE_FEE, outputs: [{ to: ADDR_CD, value: 100000000 }] } });
  check("structured cairnx view keeps the transfers-funds-OUT warning + warn slot", /transfers funds out/i.test(withOuts) && withOuts.includes('id="send-warn"'));
}

// ─── 4) wallet integration: API degradation + the transfer propose pipeline ──────
async function main() {
  const origFetch = (globalThis as any).fetch;
  const CC = mkCoin(100e8); const COIN = CC.coin; // real source-tx-derived coin so /tx verification passes
  try {
    // (a) API unreachable → { ok:false }, NEVER a throw (the popup keeps the CSD UI + quiet retry)
    (globalThis as any).fetch = async () => { throw new Error("ECONNREFUSED"); };
    const w = new Wallet(memoryStore()); await w.create("pw-cairnx-test");
    check("cairnxAssets degrades to {ok:false} when API is down (no throw)", (await w.cairnxAssets()).ok === false);
    check("cairnxTokens degrades to {ok:false} when API is down (no throw)", (await w.cairnxTokens()).ok === false);
    (globalThis as any).fetch = async () => ({ ok: false, status: 502, json: async () => ({}) });
    check("cairnxAssets degrades on a 5xx too", (await w.cairnxAssets()).ok === false);
    (globalThis as any).fetch = async () => ({ ok: true, status: 200, json: async () => { throw new Error("bad json"); } });
    check("cairnxAssets degrades on garbled JSON", (await w.cairnxAssets()).ok === false);

    // (b) happy-path reads parse the documented shapes
    (globalThis as any).fetch = async (url: any) => {
      const u = String(url);
      if (u.includes("/cairnx/address/")) return { ok: true, status: 200, json: async () => ({ address: "0xa", balances: { CAIRN: { available: "150000000", locked: "50000000" } }, names: ["satoshi"] }) };
      if (u.includes("/cairnx/tokens")) return { ok: true, status: 200, json: async () => ([{ ticker: "CAIRN", decimals: 8, name: "Cairn", supply: "2100000000000000" }]) };
      return { ok: false, status: 404, json: async () => ({}) };
    };
    const assets = await w.cairnxAssets();
    check("cairnxAssets returns balances {available,locked} + names", assets.ok === true
      && assets.balances!.CAIRN.available === "150000000" && assets.balances!.CAIRN.locked === "50000000" && assets.names![0] === "satoshi");
    const toks = await w.cairnxTokens();
    check("cairnxTokens returns the token list (decimals for display)", toks.ok === true && toks.tokens![0].ticker === "CAIRN" && toks.tokens![0].decimals === 8);

    // (c) cairnxTransfer anchors the EXACT canonical record through the propose pipeline
    let submitted: any = null;
    (globalThis as any).fetch = async (url: any, init?: any) => {
      const u = String(url);
      if (u.includes("/tip")) return { ok: true, status: 200, json: async () => ({ height: 31100 }) };
      if (u.includes("/utxos/")) return { ok: true, status: 200, json: async () => ({ confirmed_balance: 100e8, utxos: [COIN] }) };
      if (u.includes("/tx/submit")) { submitted = JSON.parse(init.body); return { ok: true, status: 200, json: async () => ({ ok: true, txid: "0x" + "ee".repeat(32) }) }; }
      const tr = txReply(u, [CC]); if (tr) return tr;
      return { ok: false, status: 404, json: async () => ({}) };
    };
    const r = await w.cairnxTransfer({ ticker: "CAIRN", amount: "150000000", to: ADDR_AB.toUpperCase().replace("0X", "0x"), decimals: 8 });
    check("cairnxTransfer submits ok", r.ok === true);
    const app = submitted?.tx?.app?.Propose;
    check("…as a Propose in domain cairnx:v1", app && app.domain === CAIRNX_DOMAIN);
    check("…whose uri is the byte-exact canonical transfer record",
      app && app.uri === `{"amount":"150000000","t":"transfer","ticker":"CAIRN","to":"${ADDR_AB}","v":1}`);
    const phHex = "0x" + (app?.payload_hash ?? []).map((b: number) => b.toString(16).padStart(2, "0")).join("");
    check("…whose payload_hash commits to the uri (sha256, cairnx-core fixture)",
      phHex === "0xfbaacb83d1a004bf8a101ac303b627bdabf70a9a897fb9404eefcabd78b2d816");
    const outs: any[] = submitted?.tx?.outputs ?? [];
    const outSum = outs.reduce((a, o) => a + Number(o.value), 0);
    check("…with NO value outputs (change only) and the 0.25 CSD fee", outs.length === 1 && COIN.value - outSum === 25_000_000);
    const h = await w.history();
    check("history records the token send (ticker + human amount + recipient)",
      h[0].type === "tokenSend" && h[0].ticker === "CAIRN" && h[0].human === "1.5" && h[0].to === ADDR_AB && h[0].fee === 25_000_000);

    // (d) invalid transfers are refused BEFORE anything is signed/submitted
    submitted = null;
    let threw = false; try { await w.cairnxTransfer({ ticker: "CAIRN", amount: "0", to: ADDR_AB }); } catch { threw = true; }
    check("cairnxTransfer refuses a zero amount (nothing submitted)", threw && submitted === null);
    threw = false; try { await w.cairnxTransfer({ ticker: "CAIRN", amount: "1", to: "0xdead" }); } catch { threw = true; }
    check("cairnxTransfer refuses a bad recipient (nothing submitted)", threw && submitted === null);
    threw = false; try { await w.cairnxTransfer({ ticker: "CAIRN", amount: "1", to: ADDR_AB, fee: 1 }); } catch { threw = true; }
    check("cairnxTransfer refuses a below-floor anchor fee", threw && submitted === null);
    w.lock();
    threw = false; try { await w.cairnxTransfer({ ticker: "CAIRN", amount: "1", to: ADDR_AB }); } catch { threw = true; }
    check("cairnxTransfer refuses when locked", threw);
  } finally { (globalThis as any).fetch = origFetch; }

  // ── audit follow-up (2026-06-12): the precise gaps the adversarial review listed ──
  {
    // parseUnits hostile inputs
    for (const bad of ["0x10", "1e5", "١٢٣", "１２３", ".", ".5", "+5", "--1"]) {
      check(`parseUnits rejects hostile "${bad}"`, parseUnits(bad, 8) === null);
    }
    // structured render REQUIRES the payload-hash commitment (render == execute)
    const t = buildTransfer({ ticker: "CAIRN", amount: "1", to: "0x" + "ab".repeat(20) });
    check("decode WITHOUT payloadHash → RAW (hash-less propose can never execute)",
      decodeCairnxRecord(t.uri, undefined) === null);
    check("decode with the correct hash → structured", decodeCairnxRecord(t.uri, t.payloadHash) !== null);
    // duplicate JSON keys → canonical-form check kills it
    const dup = '{"amount":"1","amount":"2","t":"transfer","ticker":"CAIRN","to":"0x' + "ab".repeat(20) + '","v":1}';
    check("duplicate-key uri → RAW", decodeCairnxRecord(dup, t.payloadHash) === null);
    // unicode lookalike ticker (Cyrillic С) → schema reject
    const cyr = { amount: "1", t: "transfer", ticker: "\u0421AIRN", to: "0x" + "ab".repeat(20), v: 1 };
    const cyrUri = canonicalJson(cyr);
    check("unicode-lookalike ticker → RAW", decodeCairnxRecord(cyrUri, cairnxPayloadHash(cyr)) === null);
    // the 512-byte consensus cap: per-field caps (memo ≤ 64 etc.) mean NO schema-valid record
    // can reach 512 bytes — the byte gate is defense-in-depth. Assert both halves of that:
    const maxMemo = { give: { ticker: "CAIRN", amount: "1" }, memo: "x".repeat(64), t: "offer", v: 1, want: { value: "1" } };
    const mm = canonicalJson(maxMemo);
    check("maximal legal record decodes (well under 512B: " + new TextEncoder().encode(mm).length + ")",
      new TextEncoder().encode(mm).length < 512 && decodeCairnxRecord(mm, cairnxPayloadHash(maxMemo)) !== null);
    const huge = '{"pad":"' + "x".repeat(520) + '","t":"offer","v":1}';
    check("over-512-byte uri → RAW at the byte gate", decodeCairnxRecord(huge, cairnxPayloadHash(JSON.parse(huge))) === null);
    // offer extras render structurally: taker / min / bid / token-want fixtures decode
    for (const rec of [
      { give: { ticker: "CAIRN", amount: "5" }, t: "offer", taker: "0x" + "cd".repeat(20), v: 1, want: { value: "9" } },
      { give: { ticker: "CAIRN", amount: "5" }, min: "1", t: "offer", taker: "0x" + "cd".repeat(20), v: 1, want: { value: "9" } },
      { bid: "0x" + "11".repeat(32), give: { ticker: "CAIRN", amount: "5" }, t: "offer", taker: "0x" + "cd".repeat(20), v: 1, want: { value: "9" } },
      { give: { ticker: "CAIRN", amount: "5" }, t: "offer", v: 1, want: { ticker: "XE5XNS", amount: "2" } },
    ]) {
      const u = canonicalJson(rec);
      check(`offer variant decodes (${Object.keys(rec).filter(k=>["taker","min","bid"].includes(k)).join("+")||"token-want"})`,
        decodeCairnxRecord(u, cairnxPayloadHash(rec)) !== null);
    }
    // null-vs-absent: taker:null is NOT schema-valid → RAW
    const nullTaker = { give: { ticker: "CAIRN", amount: "5" }, t: "offer", taker: null, v: 1, want: { value: "9" } };
    check("taker:null → RAW (null is not absent)", decodeCairnxRecord(canonicalJson(nullTaker), cairnxPayloadHash(nullTaker)) === null);

    // F2 mirror (well-formedness): a lone/unpaired UTF-16 surrogate has NO valid UTF-8 form, so its
    // canonical encoding is undefinable across languages — the resolver no-ops it. The trap: it PASSES
    // the canonical+hash gate (the uri is pure-ASCII `\uXXXX`), so without a dedicated check the wallet
    // would render a structured action the resolver will silently ignore. Must show RAW.
    {
      const LS = "\uD800"; // lone high surrogate
      // a) lone surrogate in a VALUE (transfer memo) — otherwise schema-valid
      const surMemo = { amount: "1", memo: "x" + LS, t: "transfer", ticker: "CAIRN", to: "0x" + "ab".repeat(20), v: 1 };
      const surMemoUri = canonicalJson(surMemo);
      check("lone surrogate survives the canonical gate (the trap)", surMemoUri.includes("\\ud800"));
      check("lone-surrogate memo → RAW (F2 mirror — resolver would no-op it)", decodeCairnxRecord(surMemoUri, cairnxPayloadHash(surMemo)) === null);
      // b) lone surrogate in a NESTED value (deploy name)
      const surName = { decimals: 0, mint: "issuer", name: "Bad" + LS, supply: "100", t: "deploy", ticker: "BAD", v: 1 };
      check("lone-surrogate token name → RAW", decodeCairnxRecord(canonicalJson(surName), cairnxPayloadHash(surName)) === null);
      // c) a well-formed non-BMP char (paired surrogates, e.g. an emoji) is FINE — not over-rejected
      const okEmoji = { amount: "1", memo: "gift 🪙", t: "transfer", ticker: "CAIRN", to: "0x" + "ab".repeat(20), v: 1 };
      check("paired surrogate (emoji memo) still decodes (no over-rejection)", decodeCairnxRecord(canonicalJson(okEmoji), cairnxPayloadHash(okEmoji)) !== null);
    }
  }

  {
    // ── security review HIGH-1: a bare attest carrying the token-fill marker (confidence 1e6)
    // is byte-identical to a token-priced fillOffer and MUST raise the loud token-spend warning ──
    const WARN = "SPENDS TOKENS";
    const attestFill = describe({ method: "attest", params: { proposalId: "0x" + "ab".repeat(32), score: 5, confidence: 1_000_000, fee: 5_000_000 } });
    check("attest + confidence=1e6 → loud TOKEN-PRICED FILL warning (HIGH-1)", attestFill.includes(WARN));
    const attestPlain = describe({ method: "attest", params: { proposalId: "0x" + "ab".repeat(32), score: 5, confidence: 100, fee: 5_000_000 } });
    check("attest with ordinary confidence → NO token warning (no false alarm)", !attestPlain.includes(WARN));
    // the cost line must also mention the token debit on the attest path
    const cost = costLine({ method: "attest", params: { confidence: 1_000_000, fee: 5_000_000 } });
    check("attest token-fill cost line mentions the token debit", /tokens debited/i.test(cost));
    // fillOffer (the already-tested path) still warns - parity check
    const fill = describe({ method: "fillOffer", params: { proposalId: "0x" + "cd".repeat(32), confidence: 1_000_000, score: 100, fee: 5_000_000, outputs: [] } });
    check("fillOffer + confidence=1e6 still warns (parity)", fill.includes(WARN));
  }

  {
    // ── audit XREPO-1: .csd name resolution is server-trusted (the wallet has no light client) ──
    // The proportionate mitigation: (1) an unmissable "verify the full address — a malicious server
    // could substitute it" caution on every named send, and (2) a confirm-time re-resolve that REFUSES
    // if the address changed between review and confirm. (Trustless resolution = the light client; see
    // SECURITY-ROADMAP. This guard stops a server that RE-POINTS the name mid-flow, the realistic case.)
    const NAME = "alice";
    const REVIEWED = "0x" + "22".repeat(20);   // address the user reviewed
    const ATTACKER = "0x" + "11".repeat(20);   // where a hostile server later re-points the name

    // (1) the name caution is surfaced + names it + tells the user to verify the To address + escapes it
    const caution = nameCautionHtml(NAME);
    check("XREPO-1: name caution warns a malicious server could substitute the address",
      /malicious or intercepted server could substitute/i.test(caution) && /verify the full address/i.test(caution));
    check("XREPO-1: name caution names the recipient + points at the To row to verify",
      caution.includes(`${NAME}.csd`) && /<b>To<\/b>/.test(caution));
    const evilName = nameCautionHtml('a<img src=x onerror=alert(1)>');
    check("XREPO-1: name caution HTML-escapes the name (no injection)",
      !evilName.includes("<img") && evilName.includes("&lt;img"));

    // H1 (NSPV-CLAIMCAP-1): a viaFill (purchased) name renders the SPECIFIC "acquired by fill, not name-scope
    // provable" caution — never the green verified badge and never the generic "couldn't verify" message.
    const viaFillCaution = nameCautionHtml(NAME, false, { viaFill: true });
    check("H1: viaFill name shows the purchase/fill-specific caution (not the generic one)",
      /acquired by an on-chain purchase|offer fill/i.test(viaFillCaution) && !/malicious or intercepted server/i.test(viaFillCaution));
    check("H1: viaFill caution is never a green ✓ verified badge", !viaFillCaution.includes("✓"));

    // (2) confirm-time guard — the core defense. THE EXPLOIT: server re-points the name to the attacker
    // between review and confirm → guard must REFUSE (this is the PoC's "redirect funds" turned blocked).
    check("XREPO-1 EXPLOIT BLOCKED: re-resolve to a DIFFERENT addr is refused (the redirect is caught)",
      reresolveUnchanged(REVIEWED, { ok: true, addr: ATTACKER }) === false);
    // honest flow: the name still points where the user reviewed → guard PASSES (send proceeds)
    check("XREPO-1 HONEST: re-resolve to the SAME addr passes (named send still works)",
      reresolveUnchanged(REVIEWED, { ok: true, addr: REVIEWED }) === true);
    check("XREPO-1 HONEST: re-resolve is case-insensitive on the hex (no false refusal)",
      reresolveUnchanged(REVIEWED, { ok: true, addr: REVIEWED.toUpperCase().replace("0X", "0x") }) === true);
    // fail-closed on every degraded re-resolution: lapse/error/missing/garbled/network-drop
    check("XREPO-1 FAIL-CLOSED: re-resolve {ok:false} (lapsed/error) is refused",
      reresolveUnchanged(REVIEWED, { ok: false }) === false);
    check("XREPO-1 FAIL-CLOSED: re-resolve with a missing addr is refused",
      reresolveUnchanged(REVIEWED, { ok: true }) === false);
    check("XREPO-1 FAIL-CLOSED: re-resolve with a non-string addr is refused",
      reresolveUnchanged(REVIEWED, { ok: true, addr: 12345 as any }) === false);
    check("XREPO-1 FAIL-CLOSED: re-resolve null (network drop / thrown call) is refused",
      reresolveUnchanged(REVIEWED, null) === false);

    // L7 (CONFIRMGUARD): a verification-status REGRESSION at confirm — same address, but a name that WAS
    // chain-verified at review can no longer be verified — must be refused (a source went hostile/stale).
    check("L7: verified→unverified regression at confirm (same addr) is REFUSED",
      reresolveUnchanged(REVIEWED, { ok: true, addr: REVIEWED, verified: false }, true) === false);
    check("L7: still-verified at confirm (same addr) PASSES",
      reresolveUnchanged(REVIEWED, { ok: true, addr: REVIEWED, verified: true }, true) === true);
    check("L7: a name reviewed as UNverified (caution) is not held to a regression check (no false refusal)",
      reresolveUnchanged(REVIEWED, { ok: true, addr: REVIEWED, verified: false }, false) === true);
    check("L7: back-compat — omitting reviewedVerified keeps the addr-only behavior",
      reresolveUnchanged(REVIEWED, { ok: true, addr: REVIEWED }) === true);

    // (3) behavioral: drive the REAL wallet.resolveName against a hostile server that re-points the
    // name on its SECOND read — exactly the mid-flow redirect the confirm-time guard must catch.
    const origFetch = (globalThis as any).fetch;
    try {
      let hits = 0;
      (globalThis as any).fetch = async (url: any) => {
        const u = String(url);
        if (u.includes(`/cairnx/resolve/${NAME}`)) {
          hits++;
          const addr = hits === 1 ? REVIEWED : ATTACKER;   // re-point on confirm-time read
          return { ok: true, status: 200, json: async () => ({ ok: true, name: NAME, addr, via: "nset", owner: addr }) };
        }
        return { ok: false, status: 404, json: async () => ({}) };
      };
      const w = new Wallet(memoryStore()); await w.create("pw-xrepo1");
      const review = await w.resolveName(NAME);              // review-time resolution
      check("XREPO-1 behavioral: review-time resolveName returns the reviewed addr", review.ok && review.addr === REVIEWED.toLowerCase());
      const confirm = await w.resolveName(NAME);             // confirm-time re-resolution (server re-points)
      check("XREPO-1 behavioral: a server that RE-POINTS mid-flow is caught by the confirm guard",
        reresolveUnchanged(String(review.addr), confirm) === false);
    } finally { (globalThis as any).fetch = origFetch; }
  }

  // NETNEW-STALE-OFFER-1: wallet.fillOffer re-checks the offer is still open and REFUSES on an affirmative
  // cancelled/filled (a no-op fill that would burn the payment irreversibly); it must NOT false-refuse an
  // unknown/unscanned offer (404 → proceed; the node + clear-sign remain the guards).
  {
    const origFetch = (globalThis as any).fetch;
    const PID = "0x" + "ab".repeat(32);
    const RCPT = "0x" + "cc".repeat(20);
    try {
      const w = new Wallet(memoryStore()); await w.create("pw-stale-offer");
      // (1) resolver AFFIRMATIVELY reports the offer cancelled → refuse BEFORE signing (node never reached)
      (globalThis as any).fetch = async (url: any) =>
        String(url).includes("/cairnx/offer/") ? { ok: true, status: 200, json: async () => ({ status: "cancelled" }) }
        : { ok: false, status: 404, json: async () => ({}) };
      const r1 = await w.fillOffer({ proposalId: PID, outputs: [{ to: RCPT, value: 1e7 }], fee: 5e6 });
      check("STALE-OFFER: a cancelled offer is REFUSED before signing (no-op fill blocked)",
        r1.ok === false && /cancelled|no-op fill/i.test(r1.error ?? ""));
      // (2) offer unknown to the wallet's resolver (404) → proceed past the recheck (fails later for an
      // unrelated reason, NOT a false stale-offer refusal — no over-blocking of recent/cross-resolver offers)
      (globalThis as any).fetch = async (url: any) => {
        const u = String(url);
        if (u.includes("/cairnx/offer/")) return { ok: false, status: 404, json: async () => ({}) };
        if (u.includes("/utxos/")) return { ok: true, status: 200, json: async () => ({ confirmed_balance: 0, utxos: [] }) };
        return { ok: false, status: 404, json: async () => ({}) };
      };
      const r2 = await w.fillOffer({ proposalId: PID, outputs: [{ to: RCPT, value: 1e7 }], fee: 5e6 });
      check("STALE-OFFER: a 404 (unscanned/cross-resolver) offer is NOT false-refused for staleness",
        r2.ok === false && !/no-op fill/i.test(r2.error ?? ""));
    } finally { (globalThis as any).fetch = origFetch; }
  }

  // M3 token-fill simulation: tokenFillQuote computes the token DEBIT (ask + 1% fee) for an OPEN token-want
  // offer so the clear-sign can show it; it FAILS CLOSED (ok:false → the UI keeps its loud caution, never
  // "free") for a CSD-want / closed / unreachable offer.
  {
    const origFetch = (globalThis as any).fetch;
    const PID = "0x" + "1a".repeat(32);
    try {
      const w = new Wallet(memoryStore()); await w.create("pw-tokenfill-quote");
      (globalThis as any).fetch = async (url: any) =>
        String(url).includes("/cairnx/offer/")
          ? { ok: true, status: 200, json: async () => ({ status: "open", feeBps: 100, want: { ticker: "FOO", amount: "1000" } }) }
          : { ok: false, status: 404, json: async () => ({}) };
      const q = await w.tokenFillQuote(PID);
      check("M3: token-fill quote computes ask + 1% fee (1000 + 10 = 1010 base units of FOO)",
        q.ok === true && q.ticker === "FOO" && q.amount === "1000" && q.fee === "10" && q.total === "1010" && q.estimated === false);
      // QA-4: a resolver that OMITS feeBps → estimate at the higher V16 rate (150 bps → fee 15) + flag it,
      // so the quote never UNDER-states the debit (over-stating ≤0.5% is the fail-safe direction).
      (globalThis as any).fetch = async (url: any) =>
        String(url).includes("/cairnx/offer/")
          ? { ok: true, status: 200, json: async () => ({ status: "open", want: { ticker: "FOO", amount: "1000" } }) }
          : { ok: false, status: 404, json: async () => ({}) };
      const qEst = await w.tokenFillQuote(PID);
      check("M3/QA-4: omitted feeBps → estimated at 150 bps (fee 15, total 1015), flagged estimated",
        qEst.ok === true && qEst.fee === "15" && qEst.total === "1015" && qEst.estimated === true);
      (globalThis as any).fetch = async () => ({ ok: true, status: 200, json: async () => ({ status: "open", want: { value: "500000000" } }) });
      check("M3: a CSD-want offer is NOT quoted as a token fill (fail-closed)", (await w.tokenFillQuote(PID)).ok === false);
      (globalThis as any).fetch = async () => ({ ok: true, status: 200, json: async () => ({ status: "filled", want: { ticker: "FOO", amount: "1000" } }) });
      check("M3: a non-open offer is NOT quoted (fail-closed)", (await w.tokenFillQuote(PID)).ok === false);
      (globalThis as any).fetch = async () => { throw new Error("net down"); };
      check("M3: an unreachable resolver yields ok:false (UI keeps its loud caution, never 'free')", (await w.tokenFillQuote(PID)).ok === false);
    } finally { (globalThis as any).fetch = origFetch; }
  }

  // L5: a custom RPC/API endpoint must be https (or loopback http) with NO embedded credentials.
  {
    const w = new Wallet(memoryStore()); await w.create("pw-rpc-validation");
    let credRej = false, httpRej = false, schemeRej = false, httpsOk = false, loopbackOk = false;
    try { await w.setRpc("https://user:pass@evil.example/api"); } catch { credRej = true; }
    try { await w.setApi("http://evil.example"); } catch { httpRej = true; }            // plain-http remote
    try { await w.addRpc("ftp://nope"); } catch { schemeRej = true; }
    try { await w.setRpc("https://good.example/api/rpc"); httpsOk = true; } catch { /* */ }
    try { await w.setRpc("http://localhost:8789"); loopbackOk = true; } catch { /* */ }
    check("L5: setRpc rejects an embedded-credential URL (https://user:pass@…)", credRej);
    check("L5: setApi rejects a plain-http remote URL", httpRej);
    check("L5: addRpc rejects a non-http(s) scheme", schemeRej);
    check("L5: setRpc accepts a clean https URL", httpsOk);
    check("L5: setRpc accepts http://localhost for dev", loopbackOk);
    // explorer setting (nav-only): accept presets + https/loopback custom; reject junk + embedded creds; status reflects it
    let expCairn = false, expOfficial = false, expCustom = false, expJunk = false, expCred = false;
    try { await w.setExplorer("cairn"); expCairn = (await w.status()).explorer === "cairn"; } catch { /* */ }
    try { await w.setExplorer("official"); expOfficial = (await w.status()).explorer === "official"; } catch { /* */ }
    try { await w.setExplorer("https://my-explorer.example"); expCustom = (await w.status()).explorer === "https://my-explorer.example/"; } catch { /* */ }
    try { await w.setExplorer("not-a-url"); } catch { expJunk = true; }
    try { await w.setExplorer("https://user:pass@evil.example"); } catch { expCred = true; }
    check("explorer: setExplorer('cairn') preset accepted + in status", expCairn);
    check("explorer: setExplorer('official') preset accepted", expOfficial);
    check("explorer: setExplorer(custom https) accepted", expCustom);
    check("explorer: setExplorer(junk) rejected", expJunk);
    check("explorer: setExplorer(embedded-credential URL) rejected", expCred);
    // EXP-XSS defense-in-depth: a custom explorer with href-breakout chars is canonicalized at storage
    let expNorm = false;
    try { await w.setExplorer('https://evil.example/"><img src=x>'); const stored = (await w.status()).explorer; expNorm = !/[<>"]/.test(stored) && stored.startsWith("https://evil.example/"); } catch { /* */ }
    check("explorer: malicious custom URL stored canonicalized (no raw < > \")", expNorm);
  }

  // CQ-1 (post shared-core de-dup, cairn docs/Plans/46): cairnx.ts no longer HAND-DECLARES the consensus
  // constants — it IMPORTS them from the vendored cairnx-core bundle, so there is nothing left to drift.
  // This guard now keeps the mirror COLLAPSED: (a) the bundle import is present and no consensus constant is
  // re-declared in cairnx.ts (a re-introduced hand-decl would re-open the drift gap), and (b) the live
  // re-exported VALUES still equal the bundle's (the import actually wires through).
  {
    const { readFileSync } = await import("node:fs");
    const ts = readFileSync("src/core/cairnx.ts", "utf8");
    const bundle = await import("../src/vendor/cairnx-spv.js");
    const mod = await import("../src/core/cairnx.js");
    check("CQ-1: cairnx.ts imports the convention surface from ../vendor/cairnx-spv.js (single source)",
      /from\s*["']\.\.\/vendor\/cairnx-spv\.js["']/.test(ts));
    for (const name of ["FEE_BPS", "FEE_BPS_V16", "REBATE_BPS", "MAX_RECORD_BYTES", "V18_HEIGHT", "MAX_AMOUNT", "REBATE_FLAT"]) {
      check(`CQ-1: ${name} is NOT hand-declared in cairnx.ts (imported, no second copy)`,
        !new RegExp(`\\b(?:const|let|var)\\s+${name}\\s*=`).test(ts));
    }
    for (const name of ["FEE_BPS", "FEE_BPS_V16", "REBATE_BPS", "V18_HEIGHT", "REBATE_FLAT"] as const) {
      const a = (mod as Record<string, unknown>)[name], b = (bundle as Record<string, unknown>)[name];
      check(`CQ-1: ${name} re-export equals the bundle (${a} === ${b})`, a != null && a === b);
    }
  }

  console.log(`\n${fail === 0 ? "ALL PASS" : "FAILURES"}: ${pass} passed, ${fail} failed`);
  process.exit(fail === 0 ? 0 : 1);
}
main();
